name = "SimplePIMC"
uuid = "d694d263-7f22-437b-be27-65f6053c4e83"
authors = ["jdksjfisdf <wanghaoran505@126.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0"
FileIO = "1"
JLD2 = "0"
LinearAlgebra = "1"
Statistics = "1"
